workspace 'YBBaby.xcworkspace'
project 'YBBaby.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!

target 'YBBaby' do
  
  project 'YBBaby.xcodeproj'
  
  # Pods for YBBaby
  pod 'SnapKit', '~> 4.0.0' 

#
  target 'YBBabyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YBBabyUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'YBDataFoundation' do
    project 'YBDataFoundation/YBDataFoundation.xcodeproj'
    pod 'ObjectMapper', '~> 3.1'
end


